[project]
name = "freshrss-db2meili"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdownify>=1.2.2",
    "meilisearch-python-sdk>=5.5.2",
    "mysql-connector-python>=9.5.0",
    "tqdm>=4.67.1",
]
